vich_uploader:
    db_driver: orm

    mappings:
        dishes:
            uri_prefix: /images/dishes
            upload_destination: '%kernel.project_dir%/public/images/dishes'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: false
            delete_on_remove: false

